=== sourcegraph/sourcegraph-search-examples/searchExamplesSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "name": {
                "type": "string"
            },
            "description": {
                "type": "string"
            },
            "syntax": {
                "type": "string"
            },
            "exampleLink": {
                "type": "string"
            },
            "tags": {
                "type": "array",
                "items": {
                    "type": "string",
                    "enum": [
                        "framework:oauth2",
                        "framework:react",
                        "language:assembly",
                        "language:bash",
                        "language:c",
                        "language:cpp",
                        "language:csharp",
                        "language:css",
                        "language:dart",
                        "language:elixir",
                        "language:erlang",
                        "language:go",
                        "language:graphql",
                        "language:groovy",
                        "language:haskell",
                        "language:html",
                        "language:java",
                        "language:javascript",
                        "language:kotlin",
                        "language:json",
                        "language:julia",
                        "language:lua",
                        "language:markdown",
                        "language:objective-c",
                        "language:ocaml",
                        "language:php",
                        "language:powershell",
                        "language:python",
                        "language:r",
                        "language:ruby",
                        "language:rust",
                        "language:sass",
                        "language:scala",
                        "language:sql",
                        "language:swift",
                        "language:terraform",
                        "language:typescript",
                        "language:vba",
                        "language:xml",
                        "language:yaml",
                        "language:zig",
                        "pattern_type:literal",
                        "pattern_type:regexp",
                        "pattern_type:structural",
                        "platform:docker",
                        "platform:github",
                        "platform:kubernetes",
                        "use_case:code_health",
                        "use_case:code_intelligence",
                        "use_case:code_reuse",
                        "use_case:devops",
                        "use_case:security"
                    ]
                }
            }
        },
        "required": [
            "name",
            "description",
            "syntax",
            "exampleLink",
            "tags"
        ]
    }
}

=== sourcegraph/sourcegraph-search-examples/static/examples.json
[{"name":"Rubygems vulnerability","description":"Search for diffs in the time period which could have exploited a package takeover vulnerability that RubyGems announced in May 2022.","syntax":"repo:^github\\.com/mastodon/mastodon$ file:^Gemfile\\.lock type:diff select:commit.diff.added - before:\"May 5, 2022\"","exampleLink":"https://sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fmastodon%2Fmastodon%24+file%3A%5EGemfile%5C.lock+type%3Adiff+select%3Acommit.diff.added+-+before%3A%22May+5%2C+2022%22&patternType=standard&sm=1&groupBy=author","tags":["use_case:security","language:ruby","pattern_type:literal"]},{"name":"NPM ua-parser-js vulnerability","description":"Search package.json files for the malicious versions of ua-parser-js. These malicious versions contain code that harvests passwords and mines cryptocurrency.","syntax":"file:package\\.json ua-parser-js.+(0\\.7\\.29|0\\.8\\.0|[^\\^]1\\.0\\.0) patternType:regexp","exampleLink":"https://sourcegraph.com/search?q=context:global+file:package%5C.json+ua-parser-js.%2B%280%5C.7%5C.29%7C0%5C.8%5C.0%7C%5B%5E%5C%5E%5D1%5C.0%5C.0%29&patternType=regexp&sm=1&groupBy=group","tags":["use_case:security","language:javascript","language:typescript","pattern_type:regexp"]},{"name":"NPM coa vulnerability","description":"Search package.json files for versions other than the recommended stable 2.0.2 release. Other versions contain malicious code that installs ransomware and credential harvesters.","syntax":"file:package\\.json \"coa\" NOT 2.0.2","exampleLink":"https://sourcegraph.com/search?q=context:global+file:package%5C.json+%22coa%22+NOT+2.0.2&patternType=standard&sm=1&groupBy=repo","tags":["use_case:security","language:javascript","language:typescript","pattern_type:literal"]},{"name":"React prop usage","description":"Using the \"Find references\" feature, find other locations in code where a specific React prop is being used and referenced.","syntax":"repo:^github\\.com/sourcegraph/sourcegraph$@b12df6d file:^client/web/src/SourcegraphWebApp\\.tsx","exampleLink":"https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b12df6d95ca30bfd1699f32e51dc83826201fa3b/-/blob/client/web/src/SourcegraphWebApp.tsx?L377:37-377:57#tab=references","tags":["use_case:code_intelligence","language:typescript","framework:react","pattern_type:literal"]},{"name":"OAuth2 configuration in Go","description":"View arguments passed to oauth2.Config() in order to add OAuth2 to a Go app.","syntax":"lang:Go oauth2.Config{:[args]} patternType:structural","exampleLink":"https://sourcegraph.com/search?q=context%3Aglobal+lang%3AGo+oauth2.Config%7B%3A%5Bargs%5D%7D&patternType=structural&sm=1&groupBy=repo","tags":["use_case:code_reuse","language:go","framework:oauth2","pattern_type:structural"]},{"name":"Standardizing error messages in Go","description":"A code smell for errors.New(fmt.Sprintf()) which should be replaced with fmt.Errorf()","syntax":"errors.New(fmt.Sprintf(:[args])) lang:Go patternType:structural","exampleLink":"https://sourcegraph.com/search?q=context:global+errors.New%28fmt.Sprintf%28:%5Bargs%5D%29%29+lang:Go&patternType=structural&sm=1&groupBy=repo","tags":["use_case:code_health","language:go","pattern_type:structural"]},{"name":"Missing error catches in Java","description":"Use structural search to perform a code smell in Java; find errors that are not handled.","syntax":"lang:Java try {:[_]} catch (:[e]) { } finally {:[_]} patternType:structural","exampleLink":"https://sourcegraph.com/search?q=context%3Aglobal+lang%3AJava+try+%7B%3A%5B_%5D%7D+catch+%28%3A%5Be%5D%29+%7B+%7D+finally+%7B%3A%5B_%5D%7D&patternType=structural&sm=1&groupBy=repo","tags":["language:java","use_case:code_health","pattern_type:structural"]},{"name":"How to use React hooks","description":"See examples of how other developers are using hooks in React.","syntax":"useState AND useRef (lang:javascript OR lang:TypeScript)","exampleLink":"https://sourcegraph.com/search?q=context:global+useState+AND+useRef+%28lang:javascript+OR+lang:TypeScript%29&patternType=standard&sm=0&groupBy=repo","tags":["language:javascript","language:typescript","pattern_type:literal","use_case:code_reuse"]},{"name":"NOT latest versions of Docker containers","description":"Search Dockerfiles for uses of the Alpine Linux container that isn't the latest version tag.","syntax":"file:^Dockerfile$ alpine:(.+) -content:alpine:latest patternType:regexp","exampleLink":"https://sourcegraph.com/search?q=context:global+file:%5EDockerfile%24+alpine:%28.%2B%29+-content:alpine:latest&patternType=regexp&sm=0&groupBy=repo","tags":["pattern_type:regexp","use_case:code_health","use_case:devops","platform:docker"]},{"name":"Jest testing via Jenkins CI","description":"Search repositories that have both a Jenkinsfile, and a package.json file with \"jest\"","syntax":"repo:has.file(path:^Jenkinsfile$) repo:has.file(path:^package.json$ content:'\"jest\"')","exampleLink":"https://sourcegraph.com/search?q=context%3Aglobal+repo%3Ahas.file%28path%3A%5EJenkinsfile%24%29+repo%3Ahas.file%28path%3A%5Epackage.json%24+content%3A%27%22jest%22%27%29&patternType=standard&sm=1&groupBy=repo","tags":["pattern_type:literal","use_case:devops","language:json"]},{"name":"Kubernetes deployments without label matches","description":"Retrieves a list of YAML files that have elements of Kubernetes deployments, but which lack the matchLabels property of the selector.","syntax":"select:file lang:YAML content:Deployment AND content:apps/v1 NOT content:matchLabels patternType:regexp","exampleLink":"https://sourcegraph.com/search?q=context:global+select:file+lang:YAML+content:Deployment+AND+content:apps/v1+NOT+content:matchLabels&patternType=regexp&sm=1&groupBy=repo","tags":["pattern_type:regexp","use_case:devops","language:yaml","platform:kubernetes"]},{"name":"Find usage of deprecated Github actions/checkout@v2","description":"Look in existing workflows for use of the deprecated v2 checkout action, which uses an EOL version of NodeJS.","syntax":"path:\\.github/workflows lang:yaml actions/checkout@v2","exampleLink":"https://sourcegraph.com/search?q=context:global+path:%5C.github/workflows+lang:yaml+actions/checkout%40v2&patternType=standard&sm=1&groupBy=repo","tags":["pattern_type:literal","use_case:devops","use_case:code_health","language:yaml","platform:github"]},{"name":"Find where caching can be used to speed up Github workflows","description":"Find workflows where actions/checkout is used and a test command is run, but actions/cache is not used.","syntax":"path:\\.github/workflows lang:yaml uses:\\sactions\\/checkout AND \\stest\\s NOT actions/cache","exampleLink":"https://sourcegraph.com/search?q=context:global+path:%5C.github/workflows+lang:yaml+uses:%5Csactions%5C/checkout+AND+%5Cstest%5Cs+NOT+actions/cache&patternType=regexp&sm=1&groupBy=repo","tags":["pattern_type:regexp","use_case:devops","use_case:code_health","language:yaml","platform:github"]},{"name":"How do people define k8s secrets in a YAML file?","description":"Find examples of how people are using a secrets definition file in Kubernetes.","syntax":"context:global lang:YAML file:has.content(kind: Secret) ^data patterntype:regexp","exampleLink":"https://sourcegraph.com/search?q=context:global+lang:YAML+file:has.content%28kind:+Secret%29+%5Edata&patternType=regexp&sm=1&groupBy=repo","tags":["pattern_type:regexp","use_case:devops","language:yaml","platform:kubernetes"]}]
